-- Add sample data to backlink_resources table for testing
INSERT INTO public.backlink_resources (
    user_id,
    name,
    website_link,
    submit_url,
    dr,
    traffic,
    payment_type,
    follow_type,
    platform_type,
    access_type,
    anchor_text,
    target_url,
    notes,
    status
) VALUES 
(
    'e75546a4-c495-4b69-98e1-3a1487ab0451',
    'TechCrunch Guest Post',
    'https://techcrunch.com',
    'https://techcrunch.com/submit-guest-post',
    85,
    5000000,
    'paid',
    'dofollow',
    'news',
    'premium',
    'innovative tech solutions',
    'https://example.com/tech-solutions',
    'High authority tech news site',
    'active'
),
(
    'e75546a4-c495-4b69-98e1-3a1487ab0451',
    'Medium Publication',
    'https://medium.com',
    'https://medium.com/submit',
    72,
    2000000,
    'free',
    'dofollow',
    'blog',
    'public',
    'digital marketing tips',
    'https://example.com/marketing-tips',
    'Popular blogging platform',
    'pending'
),
(
    'e75546a4-c495-4b69-98e1-3a1487ab0451',
    'Dev.to Community',
    'https://dev.to',
    'https://dev.to/new',
    68,
    800000,
    'free',
    'dofollow',
    'community',
    'public',
    'web development',
    'https://example.com/web-dev',
    'Developer community platform',
    'active'
);